### ISSUE TITLE
Playlist service deployment is failing

### ISSUE THREAD

**Issue by geoffreymantel** [scp756-221/term-project-babyshark#30]
Deployment fails with the following in the logs:

```
Traceback (most recent call last):
File "app.py", line 16, in <module>
from prometheus_flask_exporter import PrometheusMetrics
File "/opt/bitnami/python/lib/python3.8/site-packages/prometheus_flask_exporter/__init__.py", line 15, in <module>
from prometheus_client.exposition import choose_encoder
ImportError: cannot import name 'choose_encoder' from 'prometheus_client.exposition' (/opt/bitnami/python/lib/python3.8/site-packages/prometheus_client/exposition.py)
```

**Comment by geoffreymantel** [comment]
Looks related to this:

https://github.com/rycus86/prometheus_flask_exporter/pull/126

Probably a recent break. Should be fixed by pinning our prometheus_flask_exporter to version 0.20.0
